# Generated by Django 4.2.3 on 2023-09-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IPv4Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_first', models.PositiveBigIntegerField()),
                ('ip_last', models.PositiveBigIntegerField()),
                ('continent', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('stateprov', models.TextField()),
                ('city', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'IPv4 Location',
                'ordering': ['ip_first'],
            },
        ),
        migrations.CreateModel(
            name='IPv6Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_first', models.DecimalField(decimal_places=0, max_digits=100)),
                ('ip_last', models.DecimalField(decimal_places=0, max_digits=100)),
                ('continent', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('stateprov', models.TextField()),
                ('city', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'IPv6 Location',
                'ordering': ['ip_first'],
            },
        ),
    ]
