# Generated by Django 4.2.3 on 2023-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_first_integer', models.PositiveBigIntegerField()),
                ('ip_last_integer', models.PositiveBigIntegerField()),
                ('continent', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('stateprov', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'IPv4 Location',
            },
        ),
    ]
