# Generated by Django 4.2.3 on 2023-09-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ipv6location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipv6location',
            name='ip_first_integer',
        ),
        migrations.RemoveField(
            model_name='ipv6location',
            name='ip_last_integer',
        ),
        migrations.AddField(
            model_name='ipv6location',
            name='ip_first_text',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipv6location',
            name='ip_last_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
