# Generated by Django 4.2.3 on 2023-09-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ipv6location_ip_first_integer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipv4location',
            old_name='ip_first_integer',
            new_name='ip_first',
        ),
        migrations.RenameField(
            model_name='ipv4location',
            old_name='ip_last_integer',
            new_name='ip_last',
        ),
        migrations.RenameField(
            model_name='ipv6location',
            old_name='ip_first_text',
            new_name='ip_first',
        ),
        migrations.RenameField(
            model_name='ipv6location',
            old_name='ip_last_text',
            new_name='ip_last',
        ),
    ]
